### ISSUE TITLE
spdlog:  undefined reference to `fmt::v6::internal::assert_fail

### ISSUE THREAD

**Issue by jmarrec** [lefticus/cpp_weekly_game_project#10]
```sh
/home/julien/.conan/data/spdlog/1.5.0/_/_/package/9df34d57e1d38147409e41fa69c20cd1153df23b/lib/libspdlogd.a(spdlog.cpp.o): In function `fmt::v6::internal::is_integral_type(fmt::v6::internal::type)':
/tmp/c3ipr/pr_961_6_4_37/.conan/data/fmt/6.1.2/_/_/package/038baac88f4c7bfa972ce5adac1616bed8fe2ef4/include/fmt/core.h:736: undefined reference to `fmt::v6::internal::assert_fail(char const*, int, char const*)'
```

When conan runs I get a warning `WARN: spdlog/1.5.0: requirement fmt/6.1.2 overridden by your conanfile to fmt/6.0.0`

Upgrading to fmt/6.1.2 solves the problem.

On Ubuntu 18.04, gcc-9

**Comment by ddalcino** [comment]
Good catch! I never noticed that warning from conan.

This looks like the same issue (#3) reported by @kershnerd a while back. I wrote a PR for the upstream project that addresses this issue, and a couple Mac-specific fixes, here: https://github.com/lefticus/cpp_starter_project/pull/35

This kind of problem really underscores the need for continuous integration.

**Comment by lefticus** [comment]
I think this is all sorted out after my merge from cpp_starter_project just now.
